# Generated by Django 3.2.7 on 2021-11-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='Viet Nam', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='serves_pho',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='place',
            table='Place',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurant',
        ),
    ]
