# Generated by Django 3.2.7 on 2021-12-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_waiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Publication',
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(default='Viet Nam', max_length=100, verbose_name='Quốc Gia'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên địa điểm'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_hot_dogs',
            field=models.BooleanField(default=False, verbose_name='Phục vụ Hot Dog'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_pho',
            field=models.BooleanField(default=True, verbose_name='Phục vụ Phở'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_pizza',
            field=models.BooleanField(default=False, verbose_name='Phục vụ Pizza'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.article')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Source',
            },
        ),
    ]
