# Generated by Django 3.2.7 on 2021-12-14 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211202_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafefArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=200)),
                ('tag', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'CafefArticle',
            },
        ),
        migrations.CreateModel(
            name='CafefSource',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.article')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'CafefSource',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
