# Generated by Django 3.2.7 on 2021-12-14 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211214_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafefsource',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.cafefarticle'),
        ),
    ]
