# Generated by Django 3.2.7 on 2021-12-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_cafefsource_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CafefSource',
        ),
    ]
